name: API Tests - Rewrite Stuff on Changes

on:
  workflow_dispatch:
  push:

jobs:
  changed-files:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files within WDL directories
        id: changed-files
        uses: step-security/changed-files@v45
        with:
          files: "**/*.{wdl,json}"

      - name: Determine changed dirs
        id: get-dirs
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          uniqdirs=$(dirname ${ALL_CHANGED_FILES} | sort | uniq)
          echo "uniqdirs=$uniqdirs" >> $GITHUB_OUTPUT

      - name: List all changed WDL directories
        run: |
          for dir in ${{ steps.get-dirs.outputs.uniqdirs }}; do
            echo "WDL directory $dir was changed"
          done
