name: API Tests - Rewrite Stuff on Changes

on:
  workflow_dispatch:
  push:

jobs:
  changed-files:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.uniqdirs }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files within WDL directories
        id: changed-files
        uses: step-security/changed-files@v45
        with:
          files: "**/*.{wdl,json}"

      - name: Determine changed dirs
        id: get-dirs
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          uniqdirs=$(dirname ${{ steps.changed-files.outputs.all_changed_files }} | sort | uniq | jq -R . | jq -s | jq -c .)
          echo "uniqdirs=$uniqdirs" >> $GITHUB_OUTPUT

      - name: List all changed WDL directories
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Changes: ${{ steps.get-dirs.outputs.uniqdirs }}"

  api-tests-rewrite-on-changes:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.dirs }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wdl: ${{ fromJson(needs.changed-files.outputs.dirs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running API tests... ${{ matrix.wdl }}"
