name: API Tests - Rewrite Stuff on Changes

on:
  workflow_dispatch:
  push:

jobs:
  changed-files:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files within WDL directories
        id: changed-files
        uses: step-security/changed-files@v45
        with:
          files: "**/*.{wdl,json}"

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
